eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
server:
  port: 8091
spring:
  application:
    name: api-gateway
management:
  endpoints:
    web:
      exposure:
        include: '*' #health,info
  endpoint:
    health:
      show-details: always
---
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  redis:
    host: localhost
    port: 6379
